spring:
  application:
    name: spring-ai-enterprise-suite

  ai:

    model:
      chat: google-genai

    google:
      genai:
        api-key: ${GOOGLE_API_KEY}

        chat:
          options:
            model: gemini-2.5-flash


server:
  port: 8080